### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by EndErr** [Steema/BI#6]
First, can't find TeeBIRecompile.exe.
Then when trying to install in Delphi XE6 errors apears in BI.Arrays.pas 
[dcc32 Error] BI.Arrays.pas(644): E2029 Declaration expected but end of file found
and more after them.

**Comment by davidberneda** [comment]
The github repo does not contain the TeeBIRecompile.exe tool and the full sources.
Please download the full installer zip from the first link in the readme doc
